### ISSUE TITLE
Firefox bug affecting GSAP: el.getBBox() fails when el is not rendered

### ISSUE THREAD

**Issue by bfred-it** [greensock/GreenSock-JS#104]
It's a Firefox bug that ended up affecting me today: https://bugzilla.mozilla.org/show_bug.cgi?id=612118

"NS_ERROR_FAILURE" exception

I solved by setting `display: 'block'` before setting `transformOrigin: 'center center'` (and then reverting it to `display: 'none'`)

**Comment by jackdoyle** [comment]
Yeah, it's an annoying Firefox bug. I'm not entirely sure we can effectively work around it without adding a ton of logic. We may just need to tell people who run into it that they shouldn't tween/set things that aren't in the DOM or have display set to "none". If you've got any ideas/suggestions for an elegant workaround, please let me know.

**Comment by bfred-it** [comment]
If you don't want to add logic perhaps you can wrap it in `try/catch` and log a link to this issue?

**Comment by jackdoyle** [comment]
Nah, try/catch has a HUGE performance implication. I definitely want to avoid that. :( Any other ideas?

**Comment by bfred-it** [comment]
Huge? What about this workaround? http://stackoverflow.com/a/19728357
The problem with this stuff is that the dev will end up blaming GSAP. In my case it was completely silently failing for some reason, so that was not fun at all to pinpoint.

**Comment by jackdoyle** [comment]
Yeah, it was pretty huge last time I checked. The same thing was true in Flash/ActionScript. And since performance is absolutely imperative in an animation engine, I can't bring myself to add try...catch blocks anywhere in the GSAP codebase. 

I totally see what you mean about developers blaming GSAP for this sort of thing even though it's a Firefox bug. Frustrating. It seems we have to make a choice: either slow the engine down for everybody across the board (for SVG transforms at least) or keep if fast and risk some people getting the wrong idea about GSAP not working right in Firefox for SVG transforms. At this point, the latter seems preferable especially since the number of people affected would be so much fewer. I'll keep thinking about it, though. Let me know if you come up with any other ideas.

**Comment by JonDum** [comment]
Definitely prefer keeping it lean and fast. +2 for that.
