### ISSUE TITLE
v[type].apply is not a function

### ISSUE THREAD

**Issue by baptistebriel** [greensock/GreenSock-JS#119]
Hello, I have this TypeError while tweening: 

![screen shot 2015-09-28 at 12 38 04](https://cloud.githubusercontent.com/assets/2464663/10133475/d2d4ae52-65dd-11e5-8a3e-267e06bce709.png)

![screen shot 2015-09-28 at 12 38 16](https://cloud.githubusercontent.com/assets/2464663/10133479/d683af58-65dd-11e5-83cc-05adfcbf0ad6.png)

Do you maybe have any ideas? Thanks.

**Comment by jackdoyle** [comment]
It sounds like you may have an error in your code that perhaps passes in a non-function as an onComplete (or other callback). Tough to diagnose blind, but if you still need help I'd strongly encourage you to post in the forums at http://greensock.com/forums/ with a reduced test case that demonstrates the issue so that we can see what's going on in your code. 

Happy tweening!

**Comment by baptistebriel** [comment]
I found the error. It was kinda hard to figure out what was causing the issue because the error was referencing only `TweenMax.js`. After looking at every Tween that happens (and there's a lot!), there was this particular line of code:

```javascript
TweenMax.delayedCall(0.5, framework.go(href));
```

Which technically is a function... But it didn't seems to work.
Using an anonymous function fixed the error:

```javascript
TweenMax.delayedCall(0.5, function(){
    framework.go(href);
});
```

Thanks for your help! I will think about directly posting to the GSAP forums next time.

**Comment by jackdoyle** [comment]
Ah, that makes sense. Just to clarify, you said the "framework.go(href)" was a function but it actually isn't - remember, you'd be passing in the RESULT of that function because you're invoking it there. In other words:

This is a function: framework.go
This is whatever the function spits back: framework.go(href)

**Comment by baptistebriel** [comment]
True. :) Thanks Jack!
Have a nice week-end
