### ISSUE TITLE
Easing choice affects onComplete for ScrollTo plugin

### ISSUE THREAD

**Issue by artemivanyk** [greensock/GreenSock-JS#126]
Hi Jack,

The issue relevant to this discussion:
http://greensock.com/forums/topic/7125-oncomplete-doesnt-fire/

I thought maybe it deserves attention, here’s a fiddle:
https://jsfiddle.net/dfafc849/

No _onComplete_ called for the very first section.

Thanks for the great work :–)
Cheers

**Comment by jackdoyle** [comment]
Sorry about the tardy response - this was actually because that tween was shooting PAST the very top due to the fact that you were using Back.easeOut. So autoKill was getting triggered. The latest version should fix it, though. It won't allow things to go to a scrollTo value less than 0. Thanks for pointing this out.
