### ISSUE TITLE
Migrate KineticPlugin to use Konva

### ISSUE THREAD

**Issue by nmehlei** [greensock/GreenSock-JS#127]
Since KineticJS is no longer being maintained by the original developer and was effectively superseded by KonvaJS (same original codebase, just being maintained by different developer), I'd suggest duplicating the KineticPlugin to have a variant that supports Konva. Just renaming everything doesn't seem to be enough but since there shouldn't be any dramatic differences between Kinetic and Konva, this should not be that much effort.

**Comment by jackdoyle** [comment]
Thanks for the suggestion. It was too bad to see KineticJS suspended like that, but it's nice to hear that the hard work that was put into it is being carried on in KonvaJS. It's a bit of a tricky topic as it relates to our plugins because it's just not feasible to create a different plugin for every canvas library out there - we've got to focus on the ones that have the highest adoption rate (EaselJS and PixiJS come to mind). If we get a lot of requests for a KonvaJS plugin, we'll certainly consider that. 

I'm curious - did you already try simply renaming things in KineticPlugin and it didn't work? I wonder what else has changed and how much effort it will take to port the plugin over and ensure that it's working properly.

**Comment by praneybehl** [comment]
I believe it shouldn't be more than just changing of namespace from kinetic to konva since last time I checked, nothing has changed.

**Comment by nmehlei** [comment]
@jackdoyle Understandable, though my reasoning was based on the fact that this would be just a small code change whereas for example supporting PixiJS would be a completely new feature and the plugin would have to be developed from the ground up. 

But it seems like I misjudged my previous observations ... I tried to rename the namespace back in June and got errors/warnings from Konva that obsolete properties were being used. I came to the conclusion that the Plugin would need to be changed to use different properties and didn't see the corresponding code lines to make that change myself. BUT ... I was wrong ;) those were caused by my code, not by the plugin.
Maybe the version back in June had additional issues that could explain my assumptions back then, but those wouldn't matter now anyway ;)

Would a PR with a KonvaPlugin file with the corresponding namespace change be integrated?

**Comment by jackdoyle** [comment]
We don't typically integrate pull requests because we need to be intimately familiar with the entire codebase so that we can fully support it, but you can definitely submit a pull request that helps us see exactly what you're suggesting and we'd strongly consider making those (or similar) changes. Thanks again!
