### ISSUE TITLE
MorphSVG - distortion of SVG with reverse ease

### ISSUE THREAD

**Issue by oozaa** [greensock/GreenSock-JS#139]
I am trying to implement animated icons with MorphSVG. It works very nicely, but if user clicks on icon before first transition is ended it gets terribly distorted. 
This issue appears only when I am reversing ease function in order to keep same effect on icon.

Just go to http://codepen.io/anon/pen/PZaMar?editors=1010 and  click fast on icon multiple times . You will see what I am talking about.

My goal is on click reverse morph animation, but also reverse ease function from easeOut to easeIn to have same effect while reversing.
Any ideas how I could achieve my goal without this distortions, any work arounds? Suggestions?

Thanks!

**Comment by jackdoyle** [comment]
It's actually a logical impossibility to do it exactly the way you're attempting because of the nature of easing and the fact that the waves couldn't possibly line up in both position and time. It's not a bug  or problem with GSAP - it's simply impossible logically. However, the general effect you're going for should be achievable by just employing two different tweens. I demonstrate here: 

http://codepen.io/anon/pen/ZQjYwy?editors=0010

Click as fast as you want and it'll always get to the shape you're requesting smoothly. The only tradeoff is that the duration is always the same from the time you click until it finishes (I actually think that looks better anyway), and that there's more processing involved because each time a tween is created, it must map the SVG morphing dynamically from whatever place it's currently at. To counteract that, you can add some additional logic so that it always reuses the original tween unless the user clicks mid-tween and things must be recalculated on the fly:

http://codepen.io/anon/pen/ZQjGOv?editors=0010

Does that help?

By the way, the best place for questions like this is in our forums at http://greensock.com/forums/ where there's an active community. That way, others can easily benefit from the answer and it's searchable and there are other smart developers there who can pitch in ideas :) 

Happy tweening!

**Comment by oozaa** [comment]
That helps! Thanks for clarification and examples!

**Comment by jackdoyle** [comment]
No problem. Happy to help.
