### ISSUE TITLE
Adding support for Web Animations API

### ISSUE THREAD

**Issue by AndreyPoznyak** [greensock/GreenSock-JS#143]
Haven't found it in release notes. Isn't it time to add this feature?
http://caniuse.com/#search=web%20animations%20api

**Comment by jackdoyle** [comment]
Hm, could you help me understand what you had in mind? Like what's the benefit specifically? 

Perhaps I'm missing something, but the Web Animation API doesn't do anything that GSAP doesn't already do (in fact, GSAP does a lot more). If you're suggesting that we leverage the Web Animations API under the hood in GSAP, I don't really see any benefit there yet either and I definitely see some significant down sides like:

1. Only a few browsers actually support the WAAPI today, and several haven't even committed to ever supporting it. 
2. It'd require adding a bunch of code to GSAP, bloating its file size. Since so many browsers don't support it at all, we'd have to keep all of our existing code in place for compatibility, so all this extra code would have zero payoff (and a heavy cost, mostly with file size but also with performance due to the extra conditional logic) in those browsers. Even in browsers that do support WAAPI (actually no browser fully supports it yet...only a subset of the features so far), there would need to be a pretty huge benefit that it offers over GSAP's current tech and I'm not aware of any significant benefits yet. If anyone sees something I'm missing, please let me know. 
3. It's new technology that's very much under construction and there are quirks and differences among implementations in each browser so it feels like a shaky foundation to build on. The spec hasn't even been finalized yet, so what if we start building on it and then it changes underneath us? That could spell disaster for people who build something on GSAP and trust it to work and then the browser shifts underneath and breaks things. 

Again, perhaps I'm missing something here and I'm eager to hear suggestions. At the very least, I'd love to hear what benefit you had in mind when you suggested adding support for WAAPI @AndreyPoznyak. We certainly want to leverage technology to make GSAP as awesome as possible, while at the same time not sacrificing all the trust that our users put in it to "just work" across browsers.

**Comment by paradisaeidae** [comment]
Good points.
There is still strong resistance to g.chrome deprecating SMIL.
Smil has been underused, true.
Though the synchronization of sound and dom animation is replaced by...?

**Comment by neiltron** [comment]
Sorry to bump an old issue. Any thoughts on implementing something around this now that it's landed in the Safari tech preview? I think the main benefit that didn't seem to be mentioned so far is animations being executed in a separate thread.

[Here's the Safari release notes discussing it](https://developer.apple.com/safari/technology-preview/release-notes/).

**Comment by jackdoyle** [comment]
No problem, @neiltron. Happy to answer stuff like this, and appreciate the bump. 

First, a few comments about the whole "separate thread" thing:

- That only applies in very specific situations - when the **_only_** properties being animated are transforms or opacity. That's it. Add one other property and the whole thing gets relegated back to the main thread, even the transforms/opacity (at least that's my understanding). Otherwise they'd lose synchronization. 
- There are overhead costs for managing that separate thread; it's not entirely free and it's possible to overwhelm that thread too. For example, imagine loading a page where you shove a **TON** of animations of transforms to that thread when the main thread is somewhat idle. So in order to see a benefit you need to be pushing things hard enough on the main thread to justify the overhead cost of the other thread.
- I rarely see real-world examples where a typical user would even notice a difference performance-wise. GSAP is already super optimized and performant. 
- I think it's very cool that another thread can be utilized (even if it's only for a couple of properties). It's great! I'm actually hoping that browsers provide an API for the rest of us JS developers to tap into that rather than limiting it only to WAAPI. 

All that being said, there are quite a few other technicalities that make WAAPI ill-suited for usage under the hood in GSAP (at least from what I can tell today). In addition to all the reasons I mentioned above...

- How would we support the various easing options like Elastic, Bounce, SlowMo, RoughEase, etc.? From what I can tell, it's impossible with WAAPI. 
- How would we support individual transform components properly (x, y, z, scaleX, scaleY, rotation, rotationX, rotationY, skewX, skewY, etc.)? I've talked to the editors of the spec and from what I can tell, it's still impossible to fully support those in WAAPI even with their future plans for additive animation and partial support for isolated components (they're still merging x and y for example). 
- How would we support all the plugins like physics, morphing, throwProps, etc.? 

Lastly, I've run some tests and even with native implementation in Chrome, **GSAP was faster** (except for transforms which was to be expected, but I doubt it'd even be noticeable in most real-world situations).

I'd **_LOVE_** to be able to tap into the separate thread stuff on transforms by leveraging WAAPI under the hood, but I just don't see how it'd be feasible due to all the limitations (mostly the proper separation of transform components and full support for easing options). We could add a bunch of logic to conditionally tap WAAPI only when a tween uses a supported ease and the transform components aren't overlapping but that slows everything down slightly and bloats file size.

Think of it this way: would you rather GSAP be 25% larger and 15% slower across the board in order to make transforms a little bit smoother in the 1% of cases when it _might_ be noticeable? That doesn't seem like a good trade to me. 

Again, I really don't want to come off as critical of WAAPI or as if I don't appreciate what the spec authors and browsers are doing to move animation forward. I have huge respect for them and I think WAAPI is far better than CSS Animations. It's just not quite capable of supporting GSAP's rich feature set (yet). Feel free to correct me if I'm wrong about any of these assertions.

**Comment by neiltron** [comment]
Thanks for the response Jack. Really appreciate the thought you've put into this. I agree GSAP covers a much wider feature-set and it would probably get messy trying to selectively reimplement things. It seems like, at least until WAAPI implementations mature, it might be a one-or-the-other situation.
