### ISSUE TITLE
Values are being rounded when they shouldn't

### ISSUE THREAD

**Issue by Melatonin64** [greensock/GreenSock-JS#147]
Seems like this bug was introduced in 1.18.4.
Here's a codepen that shows the problem:
http://codepen.io/Melatonin64/pen/wGbLmB

With 1.18.3, same code would ease the blur (using decimal values).
However, with 1.18.4, this code rounds the blur value, so there's no easing.

**Comment by jackdoyle** [comment]
What's funny is I'd say it's the reverse - the bug was fixed in 1.18.4 :) 

As the docs say, by default CSSPlugin will round px values, thus the "new" behavior is the more accurate one. But you can easily disable that by setting autoRound:false in your tween. Does that help? 

From what I could tell, even if the values aren't rounded by GSAP, the browser does so internally (at least visually I saw the snapping to whole px values for the blur effect during the tween even though GSAP was using decimals).

**Comment by Melatonin64** [comment]
@jackdoyle Ok, thanks.
