### ISSUE TITLE
Different 3d rotation results using CSS and TweenLite.set

### ISSUE THREAD

**Issue by nicohsieh** [greensock/GreenSock-JS#148]
When applying the same rotation angles with CSS transform rotation syntax and TweenLite.set, the results are different.
Example:  ( click on the rotate button to rotate )
https://jsbin.com/fagiqumifi/1/edit?js,output

Not sure if I'm missing any point of the transform matrix in GSAP JS engine and CSS transform rotation syntax. Do they suppose to result in different rotation because of the implementation?

**Comment by jackdoyle** [comment]
This looks like an order-of-operation thing. I don't blame you for thinking it's a bug. Let me take a step back and explain the dilemma....
 
The CSS spec allows you to define a transform string with any order you want (like rotateX(), then rotateY(), then translateX(), then skewX(), or whatever) and it performs them in the order you declare. If you switch the order around, you can get drastically different results visually. This may seem really cool...but for animators, it can be an absolute mess. It's one of those "features" that sounds cool in theoretical/academic discussions, but in practical reality it wreaks havoc. 
 
For example, animators typically think in terms of absolutes, like "I want the x position to animate to ___" or "rotationX should end at ___". But if there's no consistency in the way things get applied, it becomes very messy to deal with because let's say you've got an element that has a bunch of transforms that include rotationX, rotationY, rotationZ, x, y, scaleX, etc. And then you want to animate it so that its scaleX is 0.5, and that's all you care about (keep the other transform components whatever they are at the time). How can you do it? Would you get the computed style and try to parse the values from the matrix3d and then create a whole new string that includes all the rotational/translation/skew values but edit only the scaleX part? Totally unrealistic. Pretty much nobody would do that. 
 
This is why GSAP imposes a consistent order of operation in the way it applies its transform components. You get complete independent control with perfect consistency across the board, and you don't have to try to track a bunch of values yourself manually. You just animate any component independently and GSAP ensures that things are composed into the matrix3d() in the appropriate order (the same very time). The only "down" side to this approach is that you don't get to use the native properties and impose your own (different) order for composition. 
 
In your particular case, you had transforms in a string that were defined in a non-standard order, thus when you tried to recreate that using GSAP's native properties, it looked different. 
 
As I see it, your options are:

1. Figure out what the component values are for GSAP's native properties to get the exact transform you're looking for. You could pass in your "transform" string to a tween (or set()) and inspect the _gsTransform object on the element which stores all of those values. (look at it in Dev Tools). In this case, it's rotation:16.1, rotationX:33.7, rotationY:25.7. 

2. Define a "transform" string as you were before. In some *very* rare cases, you might notice a slight difference in the way things render which has to do with the very complex parsing/interpolation of the computed matrix3d() and busting it apart into the components (when there are multiple axis of rotation, it becomes virtually impossible to distinguish certain aspects, thus approximation is necessary).

This has been covered many times in our forums. Here's another response that might be helpful: http://greensock.com/forums/topic/12681-3d-transform-issue-in-gsap-with-120deg/?p=53142

Happy tweening!

**Comment by nicohsieh** [comment]
Thank you so much for the detailed, in-depth explanation. It makes perfect sense. Apology for not catching the related threads on the forum and created this false alarm issue :)

**Comment by jackdoyle** [comment]
No problem at all. I totally understand - the forums have a LOT of info and it's not always easy to find stuff like that. Feel free to ask any questions there too - we've got some awesome people who offer their wisdom there. And of course it's fine to post issues here as well if you think there's a bug.

**Comment by nicohsieh** [comment]
Awesome. Really appreciate it! :)
