### ISSUE TITLE
Draggable assigns inline css of top 0

### ISSUE THREAD

**Issue by SammyJoeOsborne** [greensock/GreenSock-JS#150]
New updates to Draggable in the latest 1.18.5 release seem to be adding inline css styling of top 0 to draggable elements.

Rolled back to 1.18.4 and it doesn't do this.

**Comment by jackdoyle** [comment]
Hm, I'm not seeing that at all. Can you please provide a reduced test case codepen or jsfiddle? Are you sure it's not some other code on your end?

**Comment by SammyJoeOsborne** [comment]
It very well could be something on my end; Let me try to put something together to see if I can replicate. I'll post here and let you know the outcome

**Comment by SammyJoeOsborne** [comment]
OK, here it is replicated. Both Codepens have the same exact code, but the first link is with the previous version of Draggable (0.14.6), and the second is with the latest (0.14.7). You'll notice in the first, the items CSS positions are being respected while in the latest version they are all getting an inline style of top: 0.

Draggable 0.14.6: http://codepen.io/slopps/pen/aZzdQV

Draggable 0.14.7: http://codepen.io/slopps/pen/vKELmj

**Comment by jackdoyle** [comment]
Ah, I see the problem - you were applying your positioning logic **AFTER** you created the Draggable instance. When a Draggable is created, it records its starting position initially (for several reasons, one of which was to fix a bug in a particular edge case). So in your case, at the time you created the Draggables, all of the items were indeed at top:0 but then you called a function that applied some attributes that would affect the CSS and give them a different position (but of course the inline styles overrode that). The fix is pretty simple - just swap the order of your function calls:
```javascript
//old:
setupDragItems();
assignPositions();

//new:
assignPositions();
setupDragItems();
```
Make more sense now?

**Comment by SammyJoeOsborne** [comment]
Totally, I realized it later and actually wrote that in my comment above. It's preventable by just assigning position _then_ making the item Draggable rather than the other way around.

Just thought it was strange the two versions behaved differently, but you're right, not a bug!

Thanks a lot Jack
