### ISSUE TITLE
Make documentation accessible from Google

### ISSUE THREAD

**Issue by bfred-it** [greensock/GreenSock-JS#156]
Finding something in the documentation currently requires multiple clicks and long loads. 

Searching anything from Google on the other hand _instantly_ shows documentation... for AS2.

It'd be great to have the documentation crawlable to enable searching from Google.

**Comment by jackdoyle** [comment]
Ha - that's frustrating. We usually hear a lot of compliments on our docs, but I agree that it'd be good to make it as Google-friendly as possible. We'll look into it and see what's feasible. Not entirely sure what's involved with that yet. Thanks for pointing this out.

**Comment by hellol11** [comment]
Try feeding the docs into the google search console. Also, make sure you apply some SEO.

**Comment by bfred-it** [comment]
@jackdoyle what do you use for the main website? Any CMS? The most straightforward way would be to simply integrate the docs in the CMS (or whatever you have) instead of having them as separate HTML files. https://greensock.com/wp-content/themes/greensock/includes/docs/classContent.php?cid=3629&pid=&rid=&_=1466186129975

**Comment by jackdoyle** [comment]
@bfred-it the site uses WordPress primarily for this stuff. And yes, it's already in there (not separate HTML files).

**Comment by glebmachine** [comment]
To achieve this, you need to complete 3 simple steps

For example, we have this page:
http://greensock.com/docs/#/HTML5/GSAP/TweenMax/

**1 - Move navigation from hash to html5 style (history pushState)**
Now is 2016 - time to go forward (this required do that to have been crawled)
http://greensock.com/docs/#/HTML5/GSAP/TweenMax/
become
http://greensock.com/docs/HTML5/GSAP/TweenMax/

**Add meta tags**
```html
<meta name=fragment content=!>
```
This tag notify search engine crawlers that this page is SPA and need to be crawled by _escaped_fragment_ technique.

**Add server-side rendering on the fly for crawlers**
After, crawlers have been notified about _escaped_fragment_, it made one more request for source html to:
http://greensock.com/docs/HTML5/GSAP/TweenMax/?_escaped_fragment_
instead of
http://greensock.com/docs/HTML5/GSAP/TweenMax/

All requests with /_escaped_fragment_$/ should proxying to service like: https://github.com/prerender/prerender-node

Bingo!

**Comment by bfred-it** [comment]
`escaped_fragment` is deprecated though: https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

If you need the server to compose the page to serve under `escaped_fragment`, you might as well skip that and just serve `http://greensock.com/docs#/HTML5/GSAP/TweenMax/`

**Comment by glebmachine** [comment]
Yes, it is deprecated, but still works.

Another way - total rework to isomorphic application with server side pre rendering

**Comment by jackdoyle** [comment]
This should be resolved now, as we completely rebuilt the underlying tech that drives the docs. You'll also notice that there's a "download offline docs" button in the upper right! (You may need to clear your cache first). 

https://greensock.com/docs/

Enjoy!

**Comment by bfred-it** [comment]
😍 Excellent! It looks fast too!

https://www.google.it/search?q=site:https://greensock.com/docs

**Comment by bfred-it** [comment]
The last thing is to setup a redirect for the old links

http://greensock.com/docs/#/HTML5/GSAP/TweenMax/

**Comment by jackdoyle** [comment]
Great catch, @bfred-it - that should be resolved now (might need to clear your cache). 

And yeah, they're WAAAY faster than the old docs. Zero database queries. Only flat files. Pretty happy about that.
