### ISSUE TITLE
Stagger cycle option doesn't respect static values

### ISSUE THREAD

**Issue by kylesimmonds** [greensock/GreenSock-JS#171]
Using TweenMax v1.19.0, if I do this:
```
TweenMax.staggerFrom([array, of, elements], 1, {
  cycle: {
    paused: true,
    opacity: 0,
    x: function(index){
      return (index*10);
    }
  }
}, 0.3);
```
`opacity` and `paused` are `undefined` through a `console.log`. But if I do this:
```
TweenMax.staggerFrom([array, of, elements], 1, {
  cycle: {
    paused: function(){
      return true;
    },
    opacity: function(){
      return 0;
    },
    x: function(index){
      return (index*10);
    }
  }
}, 0.3);
```
Everything works as it should. So does `cycle` not accept static values by design, or is this a bug?

**Comment by kylesimmonds** [comment]
FWIW, this works, too:
```
TweenMax.staggerFrom([array, of, elements], 1, {
  paused: true,
  opacity: 0,
  cycle: {
    x: function(index){
      return (index*10);
    }
  }
}, 0.3);
```
So I'm guessing it's by design, but should static values still be accepted?

**Comment by jackdoyle** [comment]
Yep, that's exactly how it's supposed to work. The only things you tuck into "cycle" are ones that need to cycle :) 

Otherwise, it reads kinda weird, like if paused:true is inside of cycle, it looks like you want the paused value to cycle, but there are no values to choose from for the cycle - it's just a regular static value (thus it shouldn't be inside cycle:{})

**Comment by kylesimmonds** [comment]
@jackdoyle Gotcha, thank you for the explanation
