### ISSUE TITLE
Web Worker

### ISSUE THREAD

**Issue by glebmachine** [greensock/GreenSock-JS#173]
Hi!
Do you plan to move gsap into Web Worker thread?

**Comment by jackdoyle** [comment]
Nah, from my understanding that wouldn't provide any benefit whatsoever for an animation engine. It'd actually hurt performance due to the overhead of managing the other thread. I think Web Workers lose access to the DOM which is a deal-breaker for an engine that's constantly making changes to properties of DOM elements. :)

Am I misunderstanding something?

**Comment by glebmachine** [comment]
Yes and no in the same time)

With web workers you can move all calculations out of main thread. 

Main thread works with events and updating Dom, meanwhile second thread is calculate things and prepare stuff.

Little managing overhead take a place, but it's worth it)

Sometimes I've got 4-8ms timing on gsap out of 16ms. So it may be reduced to <1ms as well.

**Comment by jackdoyle** [comment]
The actual calculations that GSAP is doing are highly optimized and relatively cheap. I'd be willing to bet that the biggest delay (by **FAR**, like over 90%) is just the browser applying/rendering the changes which wouldn't be helped at all by a Web Worker. 

So let's say that 5% of the overall load is GSAP's guts...even if a Web Worker made that 10x faster (and of course it wouldn't), you'd only see a 4%-ish boost. And don't forget the extra costs involved in creating/managing the Web Worker...and then there's the fact that it's not synchronized with the main thread meaning that requestAnimationFrame events may fire and the Web Worker isn't ready yet, so the frame would be missed. 

Everything in an animation engine must be synchronized with the requestAnimationFrame cycles so that screen refreshes happen correctly...and that happens on the main thread. So I'm pretty confident that tapping into Web Workers for animation tasks is just impossible or would actually **_hurt_** performance. If you have any examples that show otherwise, I'd love to see them. It'd be awesome if we could tap into them to boost performance...I just think it'd backfire :)

**Comment by glebmachine** [comment]
I've made some tests. You're totally right.
Thank you!)
