### ISSUE TITLE
Strange bug in safari 9.1.1

### ISSUE THREAD

**Issue by cameronroe** [greensock/GreenSock-JS#177]
For some reason I get this strange issue with the rotation using:

```
TweenMax.to(
        this.$hero, 
        0.6, 
        { 
          rotationY: 10*xPos, 
          rotationX: 10*yPos,
          ease: Power1.easeOut, 
          transformPerspective: 900, 
          transformOrigin: "center"
        }
);
```
It works in the modern chrome, rotates the div around slightly, but in Safari 9, it get's cut off.

![screen shot 2016-10-31 at 8 24 19 pm](https://cloud.githubusercontent.com/assets/1614348/19876152/8922a258-9fa9-11e6-9771-18495505d22e.png)

**Comment by jackdoyle** [comment]
That's actually not related to GSAP at all - it's how Safari renders 3D layers. One could argue it's more correct...or less. Think of it like two pieces of paper laying on top of each other, and then you take the top one and rotate it on its x (or y) axis so that now it's intersecting with the paper underneath. Safari renders it as if half of the sheet is "behind" (which, again, could be considered correct even though some would argue it's unintuitive for developers). Other browsers act like the paper is floating way above the other, thus no intersection points. 

Make sense? 

One solution is to offset things on the z-axis so that there truly aren't any intersection points. 

Does that help at all?

**Comment by cameronroe** [comment]
What is the matrix3d supposed to be doing? It's setting:

```
z-index: 0;
transform-origin: 50% 50% 0px;
transform: matrix3d(0.9997672857836694, 0, 0.021572535241710444, -0.000023969483601900493, -0.001612117577509457, 0.9972037971811801, 0.07471270283125898, -0.00008301411425695443, -0.021512214057858484, -0.07473009358642427, 0.9969717336809971, -0.0011077463707566636, 0, 0, 0, 1);
```
This clearly cuts off the background. z-index is not affecting that.

**Comment by cameronroe** [comment]
Ah, it looks like I just need to set `perspective` [correctly on the parent](http://desandro.github.io/3dtransforms/docs/perspective.html).

**Comment by jackdoyle** [comment]
The matrix3d() is where all the transforms get applied (in your case rotationX and rotationY). It's just faster than concatenating individual rotations and other instructions, plus it allows us to independently control each transform component (like rotation, x, y, z, scaleX, scaleY, skewX, skewY, etc.)
