### ISSUE TITLE
Document how to use CustomEase

### ISSUE THREAD

**Issue by lorensr** [greensock/GreenSock-JS#193]
I've made an account, downloaded CustomEase, and added `CustomEase.min.js` to my project. 

`import { TimelineLite } from 'gsap'` 

works fine, but when I try: 

`import CustomEase from '../vendor/CustomEase.min.js'`

I get:

![image](https://cloud.githubusercontent.com/assets/251288/22266225/23e81f6c-e24d-11e6-86d4-8bdd40f240c5.png)

**Comment by jackdoyle** [comment]
Hm, are you using the CustomEase from inside the "commonjs-flat" folder? We provide that folder for folks like you who are using NPM/Node and want the ease of having everything loose in one folder and you can import anything from there. 

It sounds like you were using the file from inside "minified" but you didn't maintain the folder structure, so CustomEase is looking for the TweenLite.min.js file one folder up but not finding it.

**Comment by lorensr** [comment]
Thanks! Looks like I have to copy the whole `commonjs-flat` folder to my project, and then `import CustomEase from '../vendor/gsap/CustomEase'` works

**Comment by jackdoyle** [comment]
It's fine to copy the whole folder, but if you're using NPM, you shouldn't really have to - those files should already be there in the root and you can just drop the CustomEase one in too (and any bonus plugins you get from your GreenSock membership). Make sense?

**Comment by lorensr** [comment]
Sorry, no ☺️ 

I started out with only `npm i -S gsap`. When I put the single file in my root and do `import from '../CustomEase.js'`, I get:

![image](https://cloud.githubusercontent.com/assets/251288/22267991/cccec3fa-e253-11e6-9a4f-44175f6d61e0.png)

**Comment by jackdoyle** [comment]
So when you install gsap via NPM, are you saying that you do **NOT** get all the files loose in the root, like TweenMax, TweenLite, all the plugins, etc.? 

And what *exactly* did your import statement look like? Was it:
```javascript
import CustomEase from "gsap/CustomEase"; 
```
?

**Comment by lorensr** [comment]
> So when you install gsap via NPM, are you saying that you do NOT get all the files loose in the root, like TweenMax, TweenLite, all the plugins, etc.?

Correct, not in root. They're inside `node_modules/gsap/`:

![image](https://cloud.githubusercontent.com/assets/251288/22268978/8b210770-e257-11e6-9b77-feabf1317463.png)

I don't want to put `CustomEase.js` in there because `node_modules/` isn't under source control and gets regenerated during deployment.

The commented-out one is the one referenced in my last comment:

![image](https://cloud.githubusercontent.com/assets/251288/22269024/b2f6f2fa-e257-11e6-835a-c5ef41a2f04f.png)

**Comment by jackdoyle** [comment]
Oh, yeah, sorry - by "root" I meant the root of the "gsap" folder itself. :)

Okay, so you don't want to put CustomEase inside that folder, right? You want it to sit elsewhere, but pull in its dependencies from the node_modules/gsap folder? I think that's the core problem here. You'd probably need to set up some sort of alias in your build tool to link those up. 

But yeah, it should work fine if you just drop it into that "gsap" folder and import it as I described above.

**Comment by bfred-it** [comment]
From what I understand the issue here is that CustomEase requires "TweenLite", which doesn't exist. 

Given that GSAP is global, why even have require in there? No one would/should require CustomEase without TweenLite; that already doesn't work if they use plain files so it shouldn't *try* to work when using a bundler.

**Comment by jackdoyle** [comment]
Hm, I'm a little unclear about why it'd be an "issue" that CustomEase requires TweenLite - doesn't that require() statement establish that dependency so that if someone imports CustomEase, it'll know to grab TweenLite as well? 

Isn't the problem here that the require() path defined in CustomEase is expecting TweenLite in the same directory but it's not there since the file is manually being placed elsewhere by @lorensr?

And although TweenLite is indeed generally placed into the global scope by default, that's not always the case and my understanding was one of the biggest reasons for this whole packaging stuff and importing is to avoid globals. So it feels a little weird to pull out the dependency in favor of just assuming TweenLite will be global in all these environments. See what I mean?

If we remove the dependency in CustomEase, wouldn't it cause this not to work?:

```javascript
import CustomEase from "gsap/CustomEase";
```
?

**Comment by bfred-it** [comment]
The issue here specifically is that CustomEase.js is not part of the `gsap` package. Any reference to TweenLite inside CustomEase.js have to actually be resolvable by node. Look at this:

```
./index.js
./vendor/CustomEase.js
./node_modules/gsap/TweenLite.js
./node_modules/gsap/...
```

The only way either index.js or CustomEase.js should `require` TweenLite is with `require('gsap/TweenLite')`, therefore by going through node's resolution logic. You can't leave the fake `require('TweenLite')` or the relative `require('./TweenLite.js')` because the first doesn't work without aliases and the second points to an inexistent file (relative to `./vendor/CustomEase.js`)


> TweenLite is indeed generally placed into the global scope by default, that's not always the case

When is it not the case? From what I understand GSAP is still always attached to `window` so these named imports are unnecessary. People use them regardless because:
- they're standard practice;
- static analysis tools like ESLint complain otherwise;
- they don't know that GSAP is still attached globally, almost defeating the purpose of `require/import`

**Comment by lorensr** [comment]
There is no `window.gsap` in my app. 

I would prefer a version of `CustomEase.js` that imported from 'gsap' so that node understood to use the TweenLite inside `node_modules/`. The way I currently have it, I think two versions of TweenLite are going into the client bundle – the one I'm requiring from 'gsap' and the `/vendor/gsap/TweenLite` that `/vendor/gsap/CustomEase` is requiring.

**Comment by bfred-it** [comment]
That's right, there's no `window.gsap` because it's `window.TweenLite` or `com.greensock.TweenLite` and maybe `window._gsScope

**Comment by jackdoyle** [comment]
Yeah, I think we're saying the same thing regarding the placement of CustomEase being the problem. If it was placed with the rest of the GSAP files (as I assumed folks would do), it'd all work. That require() statement would find TweenLite. Done. Right? 

Again, removing the TweenLite dependency (require() statement in CustomEase) would make it impossible for folks to just import CustomEase (without also manually importing TweenMax or TweenLite). That probably wouldn't happen often I guess, but it certainly could. 

As far as the global scope, it might not be there if:

- The user defines a GreenSockGlobals object
- The environment doesn't support it. Frankly, it's hard to keep up with all the different build systems, packagers, compilers, transpilers, etc. Some seem to run browserless, and some may not even expose a global scope. Again, I'm just trying to avoid making too many assumptions.

If we switch require("./TweenLite.js") to require("gsap/TweenLite"), I can totally see how that'd solve things in this particular scenario but I fear it'd break things in other environments. Remember, folks are using GSAP in RequireJS, NPM, Browserify, Webpack, browserless environments, etc. See what I mean? 

Again, this is all solved by simply putting CustomEase.js in the "gsap" directory with all the other GSAP files. Right? Or you could manually edit the file and delete the require() statement or point it at "gsap/TweenLite" for your environment.

**Comment by bfred-it** [comment]
I'm not sure I get it. `GreenSockGlobals` is still a global.

> That probably wouldn't happen often I guess, but it certainly could.

Yes, people can also require `eslint-config-babel` without `eslint` and nobody expect that work work. CustomEase.js already doesn't work without TweenLite.js outside bundlers, so why should it inside? Especially when they're not even part of the same package.

I think you're thinking too much of outliers. In my opinion you should support "The Right Way™" (i.e. the most common or most future-proof way) and let the others adjust their workflow. With thousands of GSAP users a few complained, I think you're doing well.

I think you should outline what you support and what you don't, and setup tests for that. Nothing fancy, even, just a list of build commands that should complete without errors and respective html files that you can manually open and check for console errors.

---

Your current solution for `CustomEase.js` is "if you want to use CustomEase.js, you can't use gsap from npm." Not ideal.
 
If you don't want to remove that require, instead of distributing that commonjs-flat directory, you could have just `./custom-ease-for-npm-users/CustomEase.js` with `require('gsap/TweenLite')` inside. Plus documentation that mentions the `gsap` 1.19.1 requirement.

**Comment by jackdoyle** [comment]
> I'm not sure I get it. GreenSockGlobals is still a global.

Right, but references to "TweenLite" wouldn't work. All the GreenSock classes themselves wouldn't be at the global scope. Code would break. 

> Without bundlers, CustomEase.js already doesn't work without also loading TweenLite.js; why should it work with a bundler? Especially when they're not even part of the same package.

It should work with a bundler because the bundler is supposed to handle the dependencies, right? So that people don't need to worry about loading whatever that particular class needs? Isn't that the point of require() statements?

> Your current solution for CustomEase.js is "if you want to use CustomEase.js, you can't use gsap from npm." Not ideal.

No no, the intent was to make it easy to drop into the "gsap" directory in node_modules (or wherever people have things stored). Same with other members-only plugins. Obviously we can't put those in the standard/free NPM download, but I figured it'd be pretty simple for folks to drag their bonus files into that directory. 

> ...you could have just ./custom-ease-for-npm-users/CustomEase.js with require('gsap/TweenLite') inside. Plus documentation that mentions the gsap 1.19.1 requirement.

Do you see that style as pretty future-proof? I suppose we could alter all of the require() statements in the root directory of the NPM package so that they reference require("gsap/[CLASS_NAME]"); if that is indeed universally compatible (or close to it at least). Thoughts?

**Comment by bfred-it** [comment]
> All the GreenSock classes themselves wouldn't be at the global scope. Code would break.

Right, which code would break? CustomEase? That's _your_ code and you know how to access TweenLite globally correctly, in every case.

> It should work with a bundler because the bundler is supposed to handle the dependencies, right? 

TweenLite perhaps not a plain CustomEase dependency. Can I use the `CustomEase` class without ever also needing `TweenLite`/`TweenMax`/...?

> to make it easy to drop into the "gsap" directory in node_modules

That's not what people do, nobody store (or should store) node_modules in their repository, let alone modifying its contents, which are meant to be touched by anything but npm/yarn. Asking developers to create exceptions to this is even more bothersome than the webpack aliases.

Currently they either skip npm for gsap entirely or they have to edit those extra plugins to have `require('gsap/TweenLite')`. I'm betting that @lorensr's current build has both `gsap/TweenMax` in it and `./vendor/gsap/TweenLite.js` in it.

> we could alter all of the require() statements in the root directory of the NPM package so that they reference require("gsap/[CLASS_NAME]");

That's wouldn't change anything. Since each of those modules are already in the `gsap` package, `./[CLASS_NAME]` already points to `gsap/[CLASS_NAME]`, since it's a relative link.

**Comment by jackdoyle** [comment]
Yeah, I was talking more about users' code that could break if we just tell them to assume GSAP classes are always global. 

And yes, CustomEase isn't really usable if you don't have TweenLite (or TweenMax) loaded. 

The point I was trying to make is that if I remove that dependency, developers cannot just do this if they're only using CustomEase in a particular file:

```javascript
import CustomEase from "gsap/CustomEase"; //breaks
```

Right?

Your point is "who cares?", right? We'll just tell them to add another line to their imports in that case: 

```javascript
import TweenLite from "gsap/TweenLite";  //fixes it
```

And you're suggesting removing the `require()` from any/all plugins and Draggable, right? When people hit errors when trying to load those independently, we'll tell them to add another import statement (or two), right? 

> That wouldn't change anything. Since each of those modules are already in the gsap package, ./[CLASS_NAME] already points to gsap/[CLASS_NAME], since it's a relative link.

Wait...I thought referencing them like `"gsap/TweenLite"` would remove that relativity - it'd always point to the correct file in the GSAP NPM package regardless of where the referencing file (CustomEase in this case) sits. To be clear, I'm saying that changing ALL of the `require()` statements in the root files to be `"gsap/[CLASS_NAME]"` would solve these problems (for NPM users at least), right?

**Comment by bfred-it** [comment]
I looked in CustomEase.js and TweenLite.js is an actual dependency (via TweenLite's `easing.Ease`). Fair enough.

> Wait...I thought referencing them like "gsap/TweenLite" would remove that relativity

Let's clear this up:

- **In the npm package,** `require('gsap/TweenLite')` and `require('./TweenLite')` are identical in the root. So do whatever you want there, it doesn't matter.
- **In the zip file,** if you use `require('gsap/TweenLite')`, the user will also **need** to install the npm package.
  If `require('./vendor/gsap/commonjs-flat/CustomEase')` will always skip the sibling `./vendor/gsap/commonjs-flat/TweenLite.js` (and load `gsap/TweenLite.js` instead), why even have `TweenLite.js` in there?

This is why I was suggesting to drop that `commonjs-flat` folder and just leave the `./custom-ease-for-npm-users/CustomEase.js` file with `require('gsap/TweenLite')` in it.

- It's clear that it's for npm users only
- It works without any work for npm users
- It doesn't give the false expectation that the sibling TweenLite.js is loaded
- The users don't risk loading TweenLite twice

Only in this case `gsap/TweenLite` makes sense

**Comment by jackdoyle** [comment]
Yep, I like this idea (provide npm-specific versions of CustomEase and other bonus stuff in the zips that require("gsap/TweenLite")). Anyone have objections?

**Comment by lgraziani2712** [comment]
@jackdoyle you're talking about publish those bonus stuff into npm?

BTW, The actual solution is extremely simple, but extremely annoying:

1. Copy `CustomEase.js` to `node_modules/gsap/`
2. `import CustomEase from 'gsap/CustomEase';`

Every npm action will delete that file since is not part of the package, so you need to add it again (manually or automatically).

Though I would love if you can publish them ❤️

**Comment by bfred-it** [comment]
@lgraziani2712 that's not advised because node_modules is not supposed to be checked into a repository and, as you said, will be affected by npm operations (including npm update)

**Comment by lgraziani2712** [comment]
Sooo!! You're right, and I won't do it. Reading more carefully what you said in before, I replaced `./TweenLite` with `gsap/TweenLite` and it worked 😃 

Thank you guys

**Comment by TomerBrosh** [comment]
just removed it since using node  

else if (typeof (define) === 'function' && define.amd) { // AMD
    define(['gsap/TweenLite'], getGlobal);
  }

**Comment by borodadada** [comment]
hello, i dont know how run CustomEase  in Node Js 8, anybody write instruction! Ohh...

**Comment by jackdoyle** [comment]
@borodadada do you mean like this?: https://greensock.com/docs/NPMUsage (a new-ish page in the docs that's dedicated to this topic)

Notice that we recently (2.0.0) moved to ES modules by default (though UMD is still available), so that should make this even simpler. ( CC @TomerBrosh )

We don't deploy all the members-only bonus files via NPM for obvious reasons (if we did that, why would anyone sign up?) If you haven't read https://greensock.com/why-license, that helps explain why we handle things this way and why we believe it's ultimately better for our users. I apologize for any hassles, though.

**Comment by borodadada** [comment]
i download greensock-js-with-customease.zip and...??? different folder structure ( node_module/gsap and greensock-js-with-customease.zip ) tried to copy 

CustomEase.js in node_modules/gsap/
umd/CustomEase.js in node_modules/gsap/umd/CustomEase.js

`import CustomEase from "gsap/umd/CustomEase"; `

dont work :S ...

**Comment by jackdoyle** [comment]
@borodadada do you have a reduced test case that I can look at? It would be super helpful to see what kind of errors you're running into, how your project is set up, etc. The more minimal the better.

**Comment by borodadada** [comment]
error

import { CustomEase }  from "gsap/CustomEase";

```
D:\JS\nodjs\vue\node_modules\gsap\CustomEase.js:13
import { _gsScope, Ease } from "gsap/TweenLite";
^^^^^^
```

**Comment by jackdoyle** [comment]
@borodadada that sounds like your project isn't set up to accommodate ES modules, so you should just use the UMD ones. Like:
```javascript
import CustomEase from "gsap/umd/CustomEase"; //or wherever you put the file
```
(notice the "/umd/" in the path)

**Comment by borodadada** [comment]
jackdoyle Thanks man, you are best! Work!
Instruction: ( Node JS 8 TLS )
Download greensock-js-with-customease.zip -> go to folder bonus-files-for-npm-users
copy this structure ( file CustomEase.js and directory umd ) in node_modules/gsap
In project:  import CustomEase from "gsap/umd/CustomEase";

**Comment by kulabros** [comment]
Hi! Here's just some example / nitpick of how to use CustomEase with ES6 - webpack with gsap NPM dependencies. First of all - appropriate version download to project's gsap version must be used! I've put ES CustomEase.js from downloaded zip file (from /src/bonus-files-for-npm-users/CustomEase.js) to my vendor root - /src/vendor/gsap/CustomEase.js. There's only this one module now. Because I use npm gsap (from /node_modules/gsap/), I have error by default - undefined _gsScope. I did some debugging and discovered, that I have to change main import in CustomEase.js from "gsap/TweenLite.js" to "gsap" - so the import line looks: import { _gsScope, Ease } from "gsap". Everything works now as expected!The final import of CustomEase is: import CustomEase from "vendor/gsap/CustomEase".

**Comment by jackdoyle** [comment]
@kulabros would you mind sending me a reduced test case? I can't imagine why that'd happen, since "gsap/TweenLite.js" should indeed point to the file inside node_modules/gsap/. I wonder if there's something odd about your setup that's mapping things differently, but it's tough to troubleshoot blind. Nobody else has reported a similar issue (that I'm aware of). You're using 2.x, right?
