### ISSUE TITLE
Missing bower instruction in README.md

### ISSUE THREAD

**Issue by gibbok** [greensock/GreenSock-JS#195]
Missing bower instruction in README.md

The README.md includes information on how to include gasp dependency using npm but not using bower.

I would add a reference to bower installation in  README.md file.

**Comment by jackdoyle** [comment]
What exactly would you recommend that it says? (Sorry, I'm not very familiar with Bower).

**Comment by gibbok** [comment]
I think would be useful to just would add a reference to bower install like:

### BOWER
```javascript
bower install gsap
```

**Comment by bfred-it** [comment]
Bower is not suggested and it's known to have plenty of issues. Just skip it and use npm

**Comment by gibbok** [comment]
Thanks for sharing.

- Do you have any specific issue related to gsap and bower?

Currently we are evaluating gsap using bower in a complex application, and works just fine.
Also as gsap is available on bower a reference in the docs, IMO is reasonable.

**Comment by bfred-it** [comment]
#191 is the latest issue, but not the only one. 

I'm ok with documentation mentioning possible issues and pushing for npm usage. 

The issues are not strictly caused by bower but by the many tools that try to bring bower packages back into the node build pipeline — ignoring the fact that node_modules is there and works out of the box with all build tools.
