### ISSUE TITLE
Rotation from value -180 to value 180 does not animate

### ISSUE THREAD

**Issue by gibbok** [greensock/GreenSock-JS#196]
When an element has applied a CSS transform property as rotateZ or rotateY or rotateX with value of -180deg and animations should be to +180deg, animation is not executed:

Wrong animation example: https://jsfiddle.net/gibbok/o03gbpdz/
```
TweenMax.to(boxWdgNode, 1, {
  transform: 'rotateZ(180deg)', // no animation
  delay: 0,
  duration: 1
})
```

Wrong animation example: https://jsfiddle.net/gibbok/xnn2yehq/
```
TweenMax.to(boxWdgNode, 1, {
  rotationZ: 180, // no animation
  delay: 0,
  duration: 1
});

```

Desired result as browser handle it nativelly (animation is executed):

```
@keyframes spin {
  100% {
    transform: rotateZ(180deg);
  }
}
````
https://jsfiddle.net/gibbok/gyrLq4bc/

**Comment by bfred-it** [comment]
Interesting. As a temporary solution try using fromTo:
https://jsfiddle.net/xnn2yehq/3/

**Comment by gibbok** [comment]
Thanks for sharing, actually I found out a work around which consist in telling TweenMax the direction and removing 1deg.

I hope gsap team can shed some light on this issue :).

Example: https://jsfiddle.net/gibbok/31d8q7tc/
```
let boxWdgNode = document.querySelector('#boxWdgNode');
var tweenA;
tweenA = TweenMax.to(boxWdgNode, 1, {
  rotationZ: '179deg_cw',
  delay: 0,
  duration: 1
});
```

**Comment by jackdoyle** [comment]
Yes, it's actually a complexity related to interpreting 3D transforms. When you set transform-related data outside of GSAP, it must query the browser to ascertain the current values and the browser spits back a matrix() or matrix3d(). The matrix values for a rotation of 180deg and -180deg are identical. If you think about it, the object would look exactly the same either way. See what I mean? And it'd actually look the same if you had no rotation but a scaleX of -1. 

That's why we always recommend controlling/setting your transform-related values directly via GSAP because it'll record them internally and track rotational values more accurately. Another example: if you rotate beyond 360 degrees; the browser will just wrap values and there's no way to figure out how many rotations were made (the matrix()/matrix3d() values would be the same if it was rotated 360 or 720 or any multiple thereof). Plus, when you set things via GSAP directly, it's much, much faster (because the values are cached and no lookups/interpretations are necessary from the browser). 

@bfred-it's solution works because it's setting the values via GSAP rather than in the CSS and then trying to have GSAP parse them. 

Again, this isn't really a "bug" - it's just a logical impossibility due to the way matrices work.
