### ISSUE TITLE
Play with timelines

### ISSUE THREAD

**Issue by lucap86** [greensock/GreenSock-JS#199]
Quesiton 1:

```
b = new TimelineMax({paused: true})
a = new TimelineMax()
b.add(a,0)
a.call(function(){console.log(1);},[], null, 0);a.call(function(){console.log(2);},[], null, 0);a.call(function(){console.log(3);},[], null, 0);a.call(function(){console.log(4);},[], null, 0);
b.play()
```

produce output 
```
1
2
3
4
```

After this output b.play()  or b.play(0) does not produce any output.
is this a bug?

How can i do to play again timeline from the beginning?

Question 2
In the code above if i execute b.play(0) instead of b.play() it doesn't produce any output, why?

Question 3
if instead i use

```
b = new TimelineMax({paused: true})
a = new TimelineMax()
b.add(a,0)
a.call(function(){console.log(1);},[], null, 0.2);a.call(function(){console.log(2);},[], null, 0.2);a.call(function(){console.log(3);},[], null, 0.2);a.call(function(){console.log(4);},[], null, 0.2);
b.play()
```

b.play(0); works also after output

my expectation in question 1 is that if i put a call at t=0 and I play timeline from position 0 (with b.play(0)) all a.call entries (that have position=0) are executed

**Comment by joemidi** [comment]
Pretty sure it's a timing bug because both your timelines are 0 seconds long. So it doesn't really know if it's started or not.

If you added a microsecond you would have your expected results.

**Comment by lucap86** [comment]
in fact if i set 

```
b = new TimelineMax({paused: true})
a = new TimelineMax()
b.add(a,0.3)
a.call(function(){console.log(1);},[], null, 0);a.call(function(){console.log(2);},[], null, 0);a.call(function(){console.log(3);},[], null, 0);a.call(function(){console.log(4);},[], null, 0);
b.play()
```
all works fine

i had open an issue 3 month ago #178 with a similar time leak..

**Comment by jackdoyle** [comment]
It doesn't look like a "time leak" at all - it's what @joemidi said. You've got a timeline that literally has no time/duration whatsoever, so the playhead cannot move. I'm curious why you'd ever want or need to use it in this way. Can you help shed some light on that? 

If you really need to keep this zero-duration approach (which still confounds me), you could try b.play(-0.0001);

**Comment by lucap86** [comment]
as i said before if is execute play(0) my expectation is that everything inside the timeline is played

```
 I'm curious why you'd ever want or need to use it in this way
```

I have to schedule some functions calls in the time and wrap them all into a timeline
for example

```
b = new TimelineMax({paused: true})
a = new TimelineMax()
c = new TimelineMax()

b.add(a,0)
a.call(function(){console.log("a1");},[], null, 0);
b.add(c,0.24)
c.call(function(){console.log("c1");},[], null, 0);
b.play()
```

output
```
a1
c1
```

so try b.play(0) again after first output..

i think that if it works the first time it should work everytime isn't it?

**Comment by joemidi** [comment]
Why do you need a timeline if everything gets executed at 0 seconds?

**Comment by lucap86** [comment]
As i said:

I have to schedule some functions calls in the time and wrap them all into a timeline
for example

```
b = new TimelineMax({paused: true})
a = new TimelineMax()
c = new TimelineMax()

b.add(a,0)
a.call(function(){console.log("a1");},[], null, 0);
b.add(c,0.24)
c.call(function(){console.log("c1");},[], null, 0);
b.play()
```

output
```
a1
c1
```

so try b.play(0) again after first output..

just

```
c1
```
same issue

**Comment by jackdoyle** [comment]
Think of a timeline like an old record player, where the needle moves over the grooves and plays the music (tweens) it encounters. I understand why you're expecting play(0) to work, but that's kinda like taking the needle and moving it to....the same position. It's already at 0 and you're moving it to 0...so there's absolutely no movement to cause anything to play under the needle. See the dilemma?

If you really need that behavior, it's pretty easy to get by using extremely small amounts of time so that the "needle" is actually changing positions to trigger things. Even 0.0000001 should work. You just can't have the playhead at exactly the same position and expect it to sense a change and trigger things. I also gave you an alternate solution of play(-0.0001). Is there some reason these solutions won't work for you?

**Comment by lucap86** [comment]
i've understand all you have said and also your metaphor

i repeat my dilemma as well:
why first time i play a no-time timeline all calls are executed?
if you are right also first time no output should be returned.

anyway for me there are no problem to use -0.001 (it's enough, or +0.001 in the position) but I still think that is an error.

anyway.. whatever
thank you for your answer and for the great tool.

**Comment by yshing** [comment]
@lucap86 shouldn't really rely on GSAP for time-critical function calls unless it is something to do with animation.
GSAP implements uses RequestAnimationFrame if the browser supports.

And I guess for the play(0) cases maybe what you really wish for is restart()

**Comment by lucap86** [comment]
hi yshing
restart() as well doesn't work wit no-time timeline


```
b = new TimelineMax({paused: true})
a = new TimelineMax()
c = new TimelineMax()

b.add(a,0)
a.call(function(){console.log("a1");},[], null, 0);
b.add(c,0.24)
c.call(function(){console.log("c1");},[], null, 0);
b.play()
```
try it after output..

**Comment by jackdoyle** [comment]
The reason it works the first time is because it has never rendered before. To maximize performance, there's code internally that basically says "if the timeline is asked to render at the same time that it's currently rendered at, we can skip that because it's totally wasteful." Thus, once it has rendered there once, if you try again at exactly the same playhead position, it's purposely ignored. I don't think this is a bug at all, though I understand why in this particular case it looks that way to you. Zero-duration tweens/timelines are always a conundrum in the context of an animation platform for a bunch of reasons. For example, if the playhead lands directly on it, should the starting or ending state be rendered? (We opt to sense parent playhead direction). But again, it's very easy to work around the issue you brought up once you understand the mechanics.
