### ISSUE TITLE
Draggable single axis lockAxis bug

### ISSUE THREAD

**Issue by tombigel** [greensock/GreenSock-JS#202]
I am trying to implement a slider with Draggable and came across an annoying behavior:

Using type:'x' (or type:'left') with draggable is supposed to do nothing but drag horizontally, ignoring the y axis.
Actual behavior is that lockAxis: true is always on, even if defined as false and if the drag starts on the y axis the x axis is "stuck".
Expected behavior (In my mind anyway) is the lockAxis for 'y' and 'top' to be disabled if only 'x' or 'left' is defined (and vise versa)

Also, text selection on the y axis is enabled when using type: 'x'.

See demo here:
http://codepen.io/tombigel/pen/pebqEB?editors=1111

**Comment by jackdoyle** [comment]
Let me guess: you're just looking at it in Chrome, right? Apparently Chrome recently changed the way mouse and pointer events are handled, and I'd certainly call part of the new behavior a bug (which I've reported to them), but ultimately it comes down to a feature in Draggable that's attempting to allow things like native touch-scrolling. It's a tricky thing because it must sense direction initially to try to figure out if the native behavior should be allowed on the event or not.

Anyway, to solve it, you should be able to simply set allowNativeTouchScrolling:false on your Draggable. Does that help?

**Comment by tombigel** [comment]
Actually, when you mention it, I did see a difference between click and tap on my Apple Trackpad in chrome recently. Didn't think much of it then.

Of course that you solution works, but what will be the affect of this on mobile interaction? 
Also, are you planning a fix or you are waiting for Chrome devs to answer?

**Comment by jackdoyle** [comment]
This issue only affects Draggable instances that are uni-directional (type: x | y | top | left) and only in Chrome. The only down side to implementing the workaround I suggested (allowNativeTouchScrolling:false) is that it won't allow native touch-scrolling in the opposite direction. So, for example, try your codepen demo on an iOS device and you'll see that you can press/drag up/down on the first one and it'll scroll the page whereas on the 2nd one it doesn't scroll the page. 

As for some other internal workaround, there isn't one that's obvious to me at this point and I'm certainly hoping Chrome fixes its behavior. I guess one solution would be for us to just remove the whole allowNativeTouchScrolling capability from Draggable so that it's not an issue (doesn't even try to allow that in situations it thinks could be appropriate), or turn it off by default. That just seems like a bummer though since I put so much time into figuring that out origially :)
