### ISSUE TITLE
1.19.1 color parsing issues

### ISSUE THREAD

**Issue by elliotgeno** [greensock/GreenSock-JS#211]
Since 1.18.0, a new way to adjust HSL values in a relative way was added... which seems to work well up to 1.19.0. But with 1.19.1, there is a bug when using it in conjunction with TimelineMax.

Check out these pens and click on the background to see the animation play.
**The first one is correct using 1.19.0:**
http://codepen.io/pyrografix/pen/YVJWbg?editors=1000
**The second one is incorrect using 1.19.1**
http://codepen.io/pyrografix/pen/BRbVeQ?editors=0100

_Notice the SVG paths have a stroke color being applied to them. But in 1.19.1 it starts to work then gets confused and inserts the shorthand string provided to the TimelineMax call instead._

Current workaround is to fall back to 1.19.0 or earlier.

**Comment by jackdoyle** [comment]
Thanks for reporting this and providing the reduced test cases. Super helpful, Elliot. We'll look into this and get back to you.

**Comment by jackdoyle** [comment]
Got it fixed in the upcoming 1.19.2 release which you can preview (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js. Better? 

Thanks again for putting together those reduced test cases. I wish everybody who reported a bug followed your example. 

Sorry about the regression.

**Comment by jackdoyle** [comment]
Should be resolved now.
