### ISSUE TITLE
PIXI visible property

### ISSUE THREAD

**Issue by cvissie** [greensock/GreenSock-JS#220]
Hi,

We upgraded to the latest version of GSAP, we use PIXI quite a bit.

```javascript
      tl.to(_view, 0.5, {alpha: 0}, 0);
      tl.set(_view, {visible: false});
```

visible: false is no longer working since the latest version, causing the application to become unusable as visible is the only property checked during interaction.

**Comment by jackdoyle** [comment]
Hm, very sorry to hear about the trouble. Any chance you could provide a reduced test case that demonstrates the problem? I just tried animating a generic object accordingly and it seemed to work just fine with those exact values, so I'm very curious to see the problem in context. Perhaps a codepen?

**Comment by cvissie** [comment]
@jackdoyle 

Here you go. Crude but effective.

https://codepen.io/cvissie/pen/EXpmBM

Using v1.19.1 it does what you expect it to do. If it fades out, it fades out to 0.5 and then does an ugly pop.

```javascript
    tl.to(rect, 0.5, {alpha: 0.5});
    tl.set(rect, {visible: false});
```

However if making use of the latest version it doesn't do that. It keeps the red rectangle visible.

**Comment by jackdoyle** [comment]
Aha! Great example - thanks so much for putting that together. Helped me identify the issue very quickly. 

The problem was that if the final value was a "falsey" value (like 0 or false), it'd be cast as a string in the final render. So in your case, visible was being set to "false" (string) instead of false (boolean). Sorry about that. It's fixed in the next release which you can preview (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Better?

**Comment by cvissie** [comment]
Perfect 👍

**Comment by OSUblake** [comment]
It'd be nice to add that to the PixiPlugin, i.e. autoAlpha. Setting visible to false provides a performance boost as transforms won't be calculated for that object or any of its children.

**Comment by jackdoyle** [comment]
Good idea, @OSUblake - it's implemented in the next update which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/PixiPlugin.min.js

Is that working well for you?

**Comment by cvissie** [comment]
@jackdoyle I think we should close this too?

autoAlpha is also a very cool addition, I like that!
