### ISSUE TITLE
SlowMo.ease yoyoMode prop doesn't go back to the exact same value

### ISSUE THREAD

**Issue by lgraziani2712** [greensock/GreenSock-JS#226]
Hello GS! Is expected to have a little difference on the animated props values when using SlowMo.ease with yoyoMode on true?

Example: we have an object with `x` and `y` props both with `1` before applying the ease. Let's say we apply the ease only on the `y` prop. Once the ease finish, `y` hasn't `1` but `0.9999999999999996`.

In this Pen I reproduced the bug: https://codepen.io/lgraziani/pen/JyjGLX?editors=0012

Thank you!

**Comment by jackdoyle** [comment]
Ah yes - this has to do with floating point rounding errors in math operations in the browser. Like open your console and type 1 - 0.7. You'll get 0.30000000000000004 instead of 0.3. Weird, I know. 

I implemented a workaround, though, in the upcoming release which you can preview (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Better?

**Comment by lgraziani2712** [comment]
Yes! It works :)

Thank you for your quickly response @jackdoyle. Fell free to close the issue now or when the new version is released.
