### ISSUE TITLE
multiple updates on child timeline

### ISSUE THREAD

**Issue by mityok** [greensock/GreenSock-JS#232]
when having a child timeline, setting specific time on main timeline would call child timeline onUpdate multiple times. 
some of the calls with time zero happen even before onStart is called.
the parent will be called onUpdate only once
[code pen logging the issue](https://codepen.io/mityok/pen/oGvbvE?editors=1010)

Edit: the issue does not reproduce on v1.19.1

**Comment by jackdoyle** [comment]
Ah yes, it's actually calling it only one extra time, and that should be fixed in the upcoming 1.20.3 release which you can preview (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Why does it seem to call it an extra time (still)? Well, a fromTo() tween is an interesting beast because it applies its starting values immediately by default (you can alter that with immediateRender:false), and then it also must do that again when the tween actually starts (because the values may have been changed outside the tween by then). So it's totally normal for it to call that onUpdate on the very same tick BEFORE onStart fires because the onStart happens right after the animation initializes (records all its starting values) and applying the "from" values must happen FIRST as a part of initialization. 

Is that causing a problem for you for some particular reason (an extra onUpdate or two)? If so, it'd be helpful if you could explain why and perhaps I can offer a solution.
