### ISSUE TITLE
infinite animation stops looping on reverse

### ISSUE THREAD

**Issue by wowzaaa** [greensock/GreenSock-JS#234]
so my current issue is that i need an infinite timeline that i can make go back and forth using the mouse wheel

https://codepen.io/rarutu/pen/VMvYwa

u will see here that reverse acts as rewind ... so if the timeline plays forward 3 times ... when u click reverse it will only go back 3 times

any suggestion on fixing this?

thanks

**Comment by jackdoyle** [comment]
I know you closed the issue, but just for the record, the behavior you noticed was correct because the playhead reached the beginning (totalTime:0) after being reversed. The time can't go backwards beyond 0. If you want to make it appear to infinitely repeat backwards, you could do something like this: 

```javascript
onReverseComplete: function() {
    //just jump ahead 100 iterations (or whatever). 
    timeline.totalTime(timeline.duration() * 100).resume();
}
```
Does that answer your question?

**Comment by wowzaaa** [comment]
this is what i did but a bit different
when everything is done loading i do this:
`timeLine.time(timeLine.time() + totalTime * 1000);`

functionality wise i think is the same

thanks
