### ISSUE TITLE
GSDevTools 'Cannot read property 'create' of undefined'

### ISSUE THREAD

**Issue by Bram-Zijp** [greensock/GreenSock-JS#237]
Hi,

I'm trying to use the new DevTools however I get the following error when importing with a name:
Cannot read property 'create' of undefined

```
import GSDevTools from '../../modules/gsap/GSDevTools'
GSDevTools.create()

```

This however works:
```
import '../../modules/gsap/GSDevTools'
GSDevTools.create()

```

**Comment by jackdoyle** [comment]
Hm, it's tough to say what the problem is without knowing your build system and configuration, but have you tried:
```javascript
import {GSDevTools} from '../../modules/gsap/GSDevTools';
```
?

Probably a silly question, but you do have the GSDevTools file there, right? (Some people don't realize it's not in the public Github repo or downloads - it's only in the bonus zip for members).
