### ISSUE TITLE
PIXI - Resolution of filters

### ISSUE THREAD

**Issue by naranjamecanica** [greensock/GreenSock-JS#238]
We need to set the resolution of the (colormatrix) filter as a property the tween options. I see that you already made a fix in this discussion: https://greensock.com/forums/topic/17264-pixi-plugin-tip/

Would be nice to see it in next release, thanks! 👍

**Comment by jackdoyle** [comment]
Sure thing. 👍

**Comment by marksyzm** [comment]
:) Nice one - do you think the filters should be automatically removed when set to a null state also? i.e. if blur is 0 and no longer in use, remove it?

**Comment by jackdoyle** [comment]
Hm, that definitely makes things more complicated internally (because it has to add/remove dynamically based on progress - it's not safe to assume it's just something that gets removed at the end because the tween could always be rewound using seek() or whatever). 

I'm curious - have you noticed much of a performance difference if there's a filter like blur:0? I'd hope that Pixi would optimize things in that case (a filter with a value of zero).

**Comment by marksyzm** [comment]
@OSUblake said perhaps using null or false would be better in this case. We worked out you could do it programmatically anyway and discussed all this in some depth here: https://greensock.com/forums/topic/17264-pixi-plugin-tip/?tab=comments#comment-78005

But yes something is happening when I apply blur because it goes to 0.5 pixel ratio on shapes used in a container. The filter padding is correct but I do get rendering issues which tells me something extra is happening.

**Comment by jackdoyle** [comment]
PixiPlugin recognizes "resolution" now in 1.20.4 👍
