### ISSUE TITLE
Can't get draggable and onClick working simultaneously?

### ISSUE THREAD

**Issue by FranCoulibaly** [greensock/GreenSock-JS#254]
I am trying to enable the user to navigate through different content on the site by either, dragging the clock-button to rotate it to different points specified to change the content or, clicking on the clock-button which also rotates to change the content. At the moment I can do one or the other, but as soon as I enable both and trigger a click event and then a drag event (or vice versa), the clock-button snaps to positions in the wrong order (but still the defined snaps).

The code is below.
```
var clockButton = document.querySelector('#clock-button');
var snaps = [0, 45, 135, 180, 225, 315, 360];
if ((window.screen.width > 1024) && (detectTouchscreen() === false)){
    var draggable = Draggable.create([clockButton], {
            type: "rotation",
            allowEventDefault: true,
            throwProps: true,
            onDrag: onRotate,
            liveSnap: function(value) {
            position = getClosestIndex((value + 360 * 99999999) % 360, snaps); //adding 360 * 999999999 in order to ensure it's always a positive rotational value
            return snaps[position];
            },
            onClick: function(){ 
                draggable[0].disable();
                if (snaps[position] === 0){
                    snaps[position] = 45;
                    draggable[0].enable();    
                } else if (snaps[position] === 45){
                    snaps[position] = 135;
                    draggable[0].enable();
                } else if (snaps[position] === 135){
                    snaps[position] = 180;
                    draggable[0].enable();
                } else if (snaps[position] === 180){
                    snaps[position] = 225;
                    draggable[0].enable(); 
                } else if etc....
                    
                }
            }
                
        });
}
```

**Comment by jackdoyle** [comment]
Hi @FranCoulibaly. Sorry to hear about the trouble. Would you mind creating a reduced test case in Codepen so that we can see what's going on? It's kinda tough to decipher by only looking at a piece of the code. For example, you reference onRotate but that function isn't included. 

Also, why do you have allowEventDefault:true? And why are you altering the contents of "snaps" on each click? Seems like there may just be a logic issue at play. 

Oh, and the best place to post questions like this is in the forums at https://greensock.com/forums where there are some super smart (and generous) people in the community ready to help. 

I'm sure we can get it figured out once there's a codepen (or jsfiddle) to peek at.

**Comment by FranCoulibaly** [comment]
Hi @jackdoyle,
Here is my jsfiddle: https://jsfiddle.net/fr8877/zpsem6mc/173/
The clockbutton element doesn't rotate at all in the jsfiddle but it does in my project. I'm guessing that its the same issue with both though...

I've put it up on the greensock forum as well as its been bugging me for quite some time now! :)

**Comment by jackdoyle** [comment]
Thanks for posting in the forums - let's handle it there instead of a github issue. 
https://greensock.com/forums/topic/18086-draggable-onclick-enable-rotation/
