### ISSUE TITLE
Dynamically `add` to timeline with `Expo`/`Power` tweens sometimes fires `onUpdate` before `onStart`

### ISSUE THREAD

**Issue by gigablox** [greensock/GreenSock-JS#259]
Demo of issue:
https://codepen.io/gigablox/pen/jzJmWd?editors=0010

You will have to refresh the page a few times before seeing it - but the `onUpdate` function will fire prematurely before `onStart` sometimes when using these easing functions.

I was able to reproduce this issue with `Power2.easeIn`, `Power3.easeIn`, `Power4.easeIn`, `Expo.easeIn`.

I haven't tried any others.

Is the approach I'm using in the pen incorrect to dynamically build out timelines?

**Comment by jackdoyle** [comment]
From what I can tell, it's all behaving exactly as expected. I think one key misunderstanding may be that onStart will ONLY fire when the playhead moves PAST 0. If a tween is rendered with the playhead at exactly 0 (which can happen), the onStart won't fire (and that's very intentional). 

Check out this forked version that reports the playhead's position: 
https://codepen.io/GreenSock/pen/7b2c0c70c686dcdf7f83d0edb0ea7865/?editors=0010

Notice that the only time the onUpdate fires before the onStart is when the playhead is at exactly 0. So it's behaving as intended. If you don't want your onUpdate to run when the tween is rendered at a time of 0, you could simply add that conditional logic to your onUpdate. See what I mean? 

The ease had nothing to do with it, FYI.

And the reason this was intermittent is because the playhead gets updated by the browser on every requestAnimationFrame and the chances of it updating such that the playhead would land EXACTLY at the start time of one of your tweens was pretty unlikely (but it happens on occasion). 

Does that clear things up?

**Comment by jackdoyle** [comment]
If the duration of the tween is literally 0, then yes, they'd fire in order (onStart, then onUpdate, then onComplete). And yes, the docs specifically say that onStart fires _"when its time changes from 0 to some other value which can happen more than once if the tween is restarted multiple times"_. 

Does that answer your question?

**Comment by gigablox** [comment]
Yes thanks for your time
