### ISSUE TITLE
There is no point using import

### ISSUE THREAD

**Issue by rockmandash** [greensock/GreenSock-JS#286]
Thank you for this wonderful library.
I want to say there is no point using import since importing gsap will add to GLOBAL.
Simply import them at the top of index.js, other files will have access under window.TweenMax, window.Power0, etc...
However, I don't recommend this way, since I don't need all ease preset, and adding all modules to global is implicit since developers start using module systems.

**Comment by jackdoyle** [comment]
Hi @rockmandash. I'm a bit confused - it sounds like you're telling people not to import...and then you're saying not to use globals either. 

I think it's entirely valid to use import because that scopes things locally. Perhaps I misunderstood what you were saying, though. 

Was there something you wanted us to address?

**Comment by rockmandash** [comment]
@jackdoyle Thank you for your fast reply.
Sorry about that I described really confusing.

Please see this minimum example.
[![Edit Gsap import](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l9887x2xyl)

The example only contains these code.
```javascript
import { Power0 } from "gsap";

console.log(window.TimelineMax);
console.log(window.Power0);
console.log(window.Power1);
console.log(window.Power2);
console.log(window.Power3);
console.log(window.ease);

```
If I import anything in ```gsap```, actually, I automatically get all the modules inside gsap in Global window.

So this pattern is really similar to polyfill (I hope browser includes gsap by default 🤣🤣🤣).
Take ```core.js``` as example, if I want to support IE11, I just simply
```javascript
// at first line of index.js
import 'core.js'
```

If I import anything in ```gsap```, I get all modules in global, I don't really need to use it the ```module way```, I just do this
```javascript
// at first line of index.js
import 'core.js'
import 'gsap'
```

**Comment by jackdoyle** [comment]
Yep, I think I understand what you mean but I'm not sure why you'd prioritize doing it that way. More typing, you're locking things to a particular object/scope, and making things less future-proof (like if GSAP 3.0 shifts away from the globals by default). Is the goal of your "issue" post just to suggest that people follow your advice about referencing things as globals like window.TimelineMax instead of directly as the import like TimelineMax?

**Comment by rockmandash** [comment]
@jackdoyle No, you misunderstood me. My goal of this issue is not suggest everybody put everything in global, instead, if I'm using module system, there won't be any GSAP module in global.
And we tree shake those things we don't want, like if I'm only using Power2 for ease, there shouldn't be Power234 in global.
Right now, gsap puts everything under global no matter what I import. **_So that's why here is the issue._**

**Comment by jackdoyle** [comment]
So you're suggesting that GSAP drop globals completely? That's probably break a LOT of code out there, so we'll likely only consider that for the next major release. I hear you, though. It's also very tricky due to the plugin system and the fact that the current API doesn't require you to specifically reference a plugin instance, thus if we implement your suggestion then tree shaking will likely have very negative side effects. See what I mean?

**Comment by rockmandash** [comment]
I didn't mean to drop GSAP global completely.
```<script />``` tag would be a very good place to use GSAP in global window.
Sorry about the tree shaking part, I shouldn't metion it.

**Comment by OSUblake** [comment]
@rockmandash Please check the docs.
https://greensock.com/docs/NPMUsage

And this thread.
https://greensock.com/forums/topic/18437-import-from-gsap-vs-from-gsapall/

The Power eases are standard. If you don't want GSAP to be installed as global, then you can do something like this.
https://codepen.io/osublake/pen/86e2d49e288686406ef93a85fa602d33
