### ISSUE TITLE
drawSVG - Gatsby (React & Typescript)

### ISSUE THREAD

**Issue by jeremyswann** [greensock/GreenSock-JS#290]
I'm trying to import **DrawSVGPlugin** into my React project but webpack throws the ol' Object is undefined spanner at me (`defaultView ` doesn't exist on `_gsScope.document` object). I have tried various import syntax:

`import { DrawSVGPlugin } from 'gsap-bonus/DrawSVGPlugin'`
`import * as DrawSVGPlugin from 'gsap-bonus/DrawSVGPlugin'`
`import 'gsap-bonus/DrawSVGPlugin'`

Only the last global import works, but it only works in development. When I build I get this type error:
```
  15 |
  16 | var _doc = _gsScope.document,
> 17 |  _getComputedStyle = _doc.defaultView
     |                           ^
  18 |          ? _doc.defaultView.getComputedStyle
  19 |          : function() {},
  20 |  _numbersExp = /(?:(-|-=|\+=)?\d*\.?\d*(?:e[\-+]?\d+)?)[0-9]/gi,


  WebpackError: TypeError: Cannot read property 'defaultView' of undefined

  - DrawSVGPlugin.js:17 Module../src/gsap-bonus/DrawSVGPlugin.js
    lib/src/gsap-bonus/DrawSVGPlugin.js:17:27
```

**Comment by jeremyswann** [comment]
It seems that `_gsScope.document` is a global object and the import DrawSVGPlugin is loading asynchronously.

DrawSVGPlugin requires the global object `_gsScope` so I've imported it after DOM using React `componentDidMount()`
```
	public componentDidMount() {
		try {
			require('../../gsap-bonus/DrawSVGPlugin.js')
		} catch (e) {
			console.error(e)
		}
	}
```

Note: The drawSVG attribute is still behaving differently from CodePen examples. More testing required...

**Comment by jackdoyle** [comment]
Hm, it kinda sounds like a loading order issue or something with Webpack. I emailed you privately with an updated DrawSVGPlugin file to test. 

Also, you mentioned that you got things working for development but when you build you get an error and that sounds like maybe a tree shaking issue. As mentioned in the [docs](https://greensock.com/docs/NPMUsage), make sure you reference the actual plugin somewhere in your code in order to avoid tree shaking problems, like: 
```javascript
const plugins = [DrawSVGPlugin]; //<- just to reference it so that it doesn’t get dumped by tree shaking.
```
Does that help at all? If not, maybe post the simplest reduced test case so we can try to run it on our end with your exact setup. 

By the way, thanks for being a Club GreenSock member!

**Comment by jeremyswann** [comment]
Ah.. [Tree Shaking](https://webpack.js.org/guides/tree-shaking/), I read that in your docs, I didn't have a clue. That makes a lot of sense to me now, webpack considers the plugin import as dead-code so it gets dropped on build.

Very helpful @jackdoyle thank you 🙇
