### ISSUE TITLE
remove px unit for strokeDashoffset

### ISSUE THREAD

**Issue by minimit** [greensock/GreenSock-JS#294]
Hello i'm tring to animate strokeDashoffset from 1 to 0, but it gets converted in unit (px) every time..

```
TweenMax.set(progress, {strokeDashoffset: '1'});
TweenMax.to(progress, 1, {strokeDashoffset: '0'});
// or
TweenMax.set(progress, {strokeDashoffset: 1});
TweenMax.to(progress, 1, {strokeDashoffset: 0});
```

Is it possible to disable the automatic unit in tweenmax? thanks i've not found anything about it

**Comment by minimit** [comment]
Yes I don't want px, I'd like to animate from 1 to 0 unitless..

**Comment by minimit** [comment]
This works thanks, `CSSPlugin.suffixMap.strokeDashoffset = "";`

But it's strange tweenmax converts also if you pass the value on apixes like `'1'`, I guess asking to change it is too much..

**Comment by jackdoyle** [comment]
I'm still struggling to understand why you'd want that changed, especially because unitless values are interpreted by the browser as px anyway. Was there harm done? Was something not working? 

And I don't think you answered me regarding DrawSVGPlugin - are you familiar with that? It might save you some hassles. When you try to manually animate strokeDashoffset, you'll likely run into problems in various browsers or at least in certain situations (we've stumbled across quite a few). Totally up to you, of course. Glad the fix worked.

**Comment by minimit** [comment]
Here it's the demo https://jsbin.com/sizucel/edit?html,css,js,output
btw I'll check out drawSvg if I get problems on browsers thanks

**Comment by jackdoyle** [comment]
Oh, that demo explains a lot. One of the optimizations GSAP makes by default is to automatically round values for CSS that use the default px unit (because browsers don't render non-whole values the vast majority of the time). So another solution in your case is to simply set autoRound:false in your tween. 

Cheers!
