### ISSUE TITLE
Adblocker for Chrome blocks ScrollToPlugin.min.js

### ISSUE THREAD

**Issue by ep-mark** [greensock/GreenSock-JS#307]
The path libs/gsap/2.0.2/src/minified/plugins/ScrollToPlugin.min.js is being blocked by Ad Blocker for Chrome. If the plugin is renamed, the file is not blocked.

Problem is reproducible with the Adblocker for Chrome - NoAds extension, using the default settings.

**Comment by jackdoyle** [comment]
That sounds like an issue with the Adblocker, not GSAP. It doesn't strike me as a very feasible (or even effective) solution to change the name because:

- It's impossible - once things are up on the cloudflare CDN, they're permanent. That's a GOOD thing because otherwise it could have huge negative effects, breaking web sites. 
- Even if we changed the name in the next release, what would stop Adblocker from just updating its URL/algorithm? It's not a robust solution at all. 
- It would confuse our users who rely on ScrollToPlugin. 
- We're not interested in playing this game with ad blockers. 

This is actually the first I've heard of something like this related to GSAP. It's used on over 7,500,000 sites including more than 50% of the awwward-winning sites! So it's seems odd/unwise for ad blockers to assume that the presence of GSAP means it's an advertisement. That's completely unwarranted.

**Comment by don4of4** [comment]
I don't disagree with your points (above), but this issue persists.  We might need to look at raising the relevant issues with the adblocker plugins or take other measures.  @ep-mark did you find a good solution?

**Comment by don4of4** [comment]
I have just raised an issue with the Adblocker team. Hopefully they can provide some guidance.

**Comment by ep-mark** [comment]
@don4of4 I reported the issue here: https://chrome.google.com/webstore/detail/adblocker-for-chrome-noad/alplpnakfeabeiebipdmaenpmbgknjce (Support tab). I couldn't see anywhere better to report it. So hopefully your request works. We don't use a CDN to deliver our libs so we were able to rename the plugin to solve the problem in the short term.

**Comment by andreas83** [comment]
2022 here, issue still exists.

**Comment by jackdoyle** [comment]
@andreas83 is there something you think we could do on our end? If some 3rd party ad blocker decides to hijack something inappropriately, I'm not sure why it'd be reported as a GSAP issue. Maybe I'm missing something.

**Comment by andreas83** [comment]
sorry for bothering you, this issue is clearly related to AdblockPlus.

**Comment by jackdoyle** [comment]
No problem, @andreas83 . I totally understand the frustration. I'm surprised they haven't fixed that yet over there.
