### ISSUE TITLE
Draggable with foreignObject doesn't work as expected in Google Chrome browser

### ISSUE THREAD

**Issue by Umer-Hayyat** [greensock/GreenSock-JS#309]
Hi, 
I have created a minimalistic code pen to replicate the scenario [CodePen](https://codepen.io/UmerHayyat/pen/RmmEGX). What I want to achieve is:

- Child (the cyan rows) should also be dragged along with the parent (greyed area)
- Child (the cyan rows) should be independently draggable within that grey area

This works fine in Microsoft Edge and FireFox desktop browsers but doesn't work in Google Chrome

**Comment by jackdoyle** [comment]
Please see the answer(s) in the cross-post here: https://greensock.com/forums/topic/20525-draggable-with-foreignobject-doesnt-work-as-expected-in-google-chrome-browser/

We definitely wouldn't recommend using foreignObject like this because browsers don't implement it reliably. It's much better to nest SVG in HTML, not the other way around :)
