### ISSUE TITLE
TweenMax method 'from' dose not stop at correct position

### ISSUE THREAD

**Issue by RhinoLu** [greensock/GreenSock-JS#311]
https://codepen.io/RhinoLu/pen/BXKVRe

Box A1 should stop at 'margin-top: 1%' just like box B1,
method 'FromTo' do stop at correct position just like box A2.

Please take a look, Thanks.

**Comment by jackdoyle** [comment]
Good catch, @RhinoLu - the problem had to do with GSAP basing percentage-based padding/margin values on the height rather than the width when it was related to top/bottom (which actually seems intuitive, but the CSS spec always uses the width). That should be fixed in the next release which you can preview (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Better?

**Comment by RhinoLu** [comment]
It is correct now. Thanks.
