### ISSUE TITLE
Problems tweening properties using calc()

### ISSUE THREAD

**Issue by OSUblake** [greensock/GreenSock-JS#87]
Before being able to tween to a property using calc(), you must first set a calc() value with GSAP. Setting an initial calc() value in CSS without setting it with GSAP makes the animation behave like a 0 duration tween.

http://codepen.io/osublake/pen/ByZPgr

**Comment by jackdoyle** [comment]
I wouldn't really consider the lack of tweening "calc()" values in GSAP to be a "bug" because it strikes me as impossible to do. That would require animating between dynamically calculated values. What if it starts at "calc(50px + [window height])" and ends at "calc(-100vh + [nav container height] + [2x nav bottom property])"? There are completely different numbers of properties, units, relative values, etc. Sure, we could apply them at the moment the tween starts and use the **_calculated_** values but that's not technically accurate. What if someone resized the window **during** the tween? See what I mean? Perhaps I'm missing something, but I'm pretty sure the only way to do this would be to force the use of computed values at a given time (start of the tween) and live with the fact that they wouldn't be dynamic during the tween at all. In other words, it'd convert to something like "235px to 131px" instead. 
 
If it were me, I'd probably just use JS since it's so dynamic by its very nature and avoid CSS calc() values altogether.

The only reason your codepen demo worked when using a TweenMax.set() initially was because of a technicality in the way CSSPlugin looks up the current values - if it finds the value in the inline style, it uses that but in all other cases it must use the computed style. If you run window.getComputedStyle(document.getElementById("tile1")).width; in your demo, you'll see that it returns "223.375px" which doesn't map nicely when tweening to "calc(100% - 10px)". But the inline style has the same quantity of numbers inside the string, thus GSAP can just parse those out and animate it as a complex string. But if you used a more or less complicated calc() value on either end, it wouldn't have worked.

**Comment by OSUblake** [comment]
It took me a while to figure out how to animate dynamic properties. It's probably not something that could easily be added to GSAP as it's pretty use-case specific. For example, to animate width and height in this [flexbox playground](http://codepen.io/osublake/pen/dMLQJr), I have to use a hidden element to calculate the value to animate to. 

http://codepen.io/osublake/pen/dMLQJr
