### ISSUE TITLE
Draggable.js: Click event triggered twice in 1.15.1.

### ISSUE THREAD

**Issue by Bragolgirith** [greensock/GreenSock-JS#88]
I've just updated to the latest release (1.15.1) and noticed that sometimes click events get handled twice. 
Codepen: http://codepen.io/anon/pen/wBygrL. 

It seems that this is caused by these new lines in Draggable.js (1348-1354):

    if (originalEvent.target.click) { //some browsers (like mobile Safari) don't properly trigger the click event
	    originalEvent.target.click();
    } else if (_doc.createEvent) {
	    syntheticEvent = _doc.createEvent("MouseEvents");
	    syntheticEvent.initEvent("click", true, true);
	    originalEvent.target.dispatchEvent(syntheticEvent);
    }

Not sure how to fix it yet, but it might be worth reverting these changes, as they might break existing code (at least in my case they do).

**Comment by jackdoyle** [comment]
Ah yes, good catch. Gotta love how differently various browsers behave and all the workarounds necessary to get consistent behavior! We can't remove that other code because it actually resolves a problem in some other browsers (like iOS) that cause it to not dispatch any click event whatsoever. Not to worry, though - I think I've got it patched up in the upcoming release. I posted it in response to a different question in the forums here: http://greensock.com/forums/topic/11272-draggable-snap-points/?p=45931 so you can snag it there and try it out.

**Comment by jackdoyle** [comment]
Fixed.
